### ISSUE TITLE
Error when using multiple networks

### ISSUE THREAD

**Issue by TamashaM** [fratajcz/speos#9]
Many thanks for the code.

I was able to run the training.py script using just one network in the adjacency matrix. However, when I try to use multiple networks, I get the following error. I tried in both branches stable and latest with the versions mentioned in your response to a [ previous issue](https://github.com/fratajcz/speos/issues/7). No luck :(

```
Traceback (most recent call last):
  File "/data/gpfs/projects/punim0512/tamasha_projects/speos/training.py", line 13, in <module>
    pipeline.run()
  File "/data/gpfs/projects/punim0512/tamasha_projects/speos/speos/pipeline.py", line 39, in run
    self.experiment.run()
  File "/data/gpfs/projects/punim0512/tamasha_projects/speos/speos/experiment.py", line 128, in run
    self.train()
  File "/data/gpfs/projects/punim0512/tamasha_projects/speos/speos/experiment.py", line 163, in train
    self.train_out, loss = self.model.step(self.data, self.data.train_mask)
  File "/data/gpfs/projects/punim0512/tamasha_projects/speos/speos/models.py", line 216, in step
    out = self(data.x, data.edge_index)
  File "/data/gpfs/projects/punim0512/tamasha_projects/speos/speos/models.py", line 75, in __call__
    return self.architectures[0](*args, **kwargs)
  File "/home/tamasha/.conda/envs/speos_v3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/gpfs/projects/punim0512/tamasha_projects/speos/speos/architectures.py", line 411, in forward
    return super().forward(x, edge_index)
  File "/data/gpfs/projects/punim0512/tamasha_projects/speos/speos/architectures.py", line 325, in forward
    x = self.mp(x_pre, edge_index)
  File "/home/tamasha/.conda/envs/speos_v3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/tamasha_pyg/tmp9zk8kle_.py", line 18, in forward
    x = self.module_0(x, edge_index)
  File "/home/tamasha/.conda/envs/speos_v3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tamasha/.conda/envs/speos_v3/lib/python3.10/site-packages/torch_geometric/nn/conv/rgcn_conv.py", line 207, in forward
    assert edge_type is not None
```

My config file
```
name: dee_test

input:
    tag: dee
    adjacency: [huri, BioPlex30293T]
mp:
    type: film

```

Package versions 
```
torch                     2.0.1+cu117      
torch-cluster             1.6.3+pt20cu117     
torch-geometric           2.3.1 
torch-scatter             2.1.2+pt20cu117    
torch-sparse              0.6.17  

```

**Comment by fratajcz** [comment]
Hi!

I just tested your config, but with the default `tag` since I don't have your "dee" gene list. 

Following config:

```
name: dee_test

input:
    adjacency: [huri, BioPlex30293T]
mp:
    type: film
```

runs fine when used with training.py:

```
(speos) ubuntu@gpu1:~/speos$ python training.py -c github_testconfig.yaml
dee_test 2024-03-19 10:26:50,119 [INFO] speos.experiment: Starting run dee_test
dee_test 2024-03-19 10:26:50,119 [INFO] speos.experiment: Cuda is available: True
dee_test 2024-03-19 10:26:50,132 [INFO] speos.experiment: Using device(s): ['cuda:0']
dee_test 2024-03-19 10:26:50,135 [INFO] speos.preprocessing.preprocessor: Using Adjacency matrices: ['BioPlex30293T', 'HuRI']
dee_test 2024-03-19 10:26:50,136 [INFO] speos.preprocessing.preprocessor: Using 9 mappings with ground truth data/mendelian_gene_sets/Immune_Dysregulation_genes.bed 
Processing...
dee_test 2024-03-19 10:27:14,612 [INFO] speos.preprocessing.preprocessor: MultiDiGraph with 17024 nodes and 240634 edges
Done!
dee_test 2024-03-19 10:27:14,980 [INFO] speos.preprocessing.preprocessor: Number of positives in ground truth data/mendelian_gene_sets/Immune_Dysregulation_genes.bed: 525
dee_test 2024-03-19 10:27:15,565 [INFO] speos.preprocessing.datasets: Loading Processed Data from ././data/processed/dee_test.pt
/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch_geometric/data/in_memory_dataset.py:157: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)
dee_test 2024-03-19 10:27:15,620 [INFO] speos.experiment: RelationalGeneNetwork(
  (pre_mp): Sequential(
    (0): Linear(93, 50, bias=True)
    (1): ELU(alpha=1.0)
    (2): Linear(50, 50, bias=True)
    (3): ELU(alpha=1.0)
    (4): Linear(50, 50, bias=True)
    (5): ELU(alpha=1.0)
    (6): Linear(50, 50, bias=True)
    (7): ELU(alpha=1.0)
    (8): Linear(50, 50, bias=True)
    (9): ELU(alpha=1.0)
    (10): Linear(50, 50, bias=True)
    (11): ELU(alpha=1.0)
  )
  (post_mp): Sequential(
    (0): Linear(50, 50, bias=True)
    (1): ELU(alpha=1.0)
    (2): Linear(50, 50, bias=True)
    (3): ELU(alpha=1.0)
    (4): Linear(50, 50, bias=True)
    (5): ELU(alpha=1.0)
    (6): Linear(50, 50, bias=True)
    (7): ELU(alpha=1.0)
    (8): Linear(50, 50, bias=True)
    (9): ELU(alpha=1.0)
    (10): Linear(50, 25, bias=True)
    (11): ELU(alpha=1.0)
    (12): Linear(25, 1, bias=True)
  )
  (mp): Sequential(
    (0): RGCNConv(50, 50, num_relations=2)
    (1): ELU(alpha=1.0)
    (2): InstanceNorm(50)
    (3): RGCNConv(50, 50, num_relations=2)
    (4): ELU(alpha=1.0)
    (5): InstanceNorm(50)
  )
)
dee_test 2024-03-19 10:27:15,592 [INFO] speos.preprocessing.datasets: HeteroData(
  x=[17024, 93],
  y=[17024],
  train_mask=[17024],
  test_mask=[17024],
  val_mask=[17024],
  gene={ x=[17024, 93] },
  (gene, BioPlex30293T, gene)={ edge_index=[2, 160962] },
  (gene, HuRI, gene)={ edge_index=[2, 79672] }
)
dee_test 2024-03-19 10:27:15,623 [INFO] speos.experiment: Cuda is available: True
dee_test 2024-03-19 10:27:17,325 [INFO] speos.experiment: Created new ResultsHandler pointing to ./results/dee_test.h5
dee_test 2024-03-19 10:27:17,408 [INFO] speos.experiment: Received data with 472 train positives, 14849 train negatives, 27 val positives, 825 val negatives, 26 test positives and 825 test negatives
dee_test 2024-03-19 10:27:17,410 [INFO] speos.experiment: Cuda is available: True
dee_test 2024-03-19 10:27:17,422 [INFO] speos.experiment: Starting run dee_test
dee_test 2024-03-19 10:27:17,422 [INFO] speos.experiment: Cuda is available: True
dee_test 2024-03-19 10:27:17,422 [INFO] speos.experiment: Using device(s): ['cuda:0']
dee_test 2024-03-19 10:27:17,425 [INFO] speos.preprocessing.preprocessor: Using Adjacency matrices: ['BioPlex30293T', 'HuRI']
dee_test 2024-03-19 10:27:17,426 [INFO] speos.preprocessing.preprocessor: Using 9 mappings with ground truth data/mendelian_gene_sets/Immune_Dysregulation_genes.bed 
dee_test 2024-03-19 10:27:17,427 [INFO] speos.preprocessing.datasets: Loading Processed Data from ././data/processed/dee_test.pt
/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch_geometric/data/in_memory_dataset.py:157: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)
dee_test 2024-03-19 10:27:17,465 [INFO] speos.experiment: RelationalGeneNetwork(
  (pre_mp): Sequential(
    (0): Linear(93, 50, bias=True)
    (1): ELU(alpha=1.0)
    (2): Linear(50, 50, bias=True)
    (3): ELU(alpha=1.0)
    (4): Linear(50, 50, bias=True)
    (5): ELU(alpha=1.0)
    (6): Linear(50, 50, bias=True)
    (7): ELU(alpha=1.0)
    (8): Linear(50, 50, bias=True)
    (9): ELU(alpha=1.0)
    (10): Linear(50, 50, bias=True)
    (11): ELU(alpha=1.0)
  )
  (post_mp): Sequential(
    (0): Linear(50, 50, bias=True)
    (1): ELU(alpha=1.0)
    (2): Linear(50, 50, bias=True)
    (3): ELU(alpha=1.0)
    (4): Linear(50, 50, bias=True)
    (5): ELU(alpha=1.0)
    (6): Linear(50, 50, bias=True)
    (7): ELU(alpha=1.0)
    (8): Linear(50, 50, bias=True)
    (9): ELU(alpha=1.0)
    (10): Linear(50, 25, bias=True)
    (11): ELU(alpha=1.0)
    (12): Linear(25, 1, bias=True)
  )
  (mp): Sequential(
    (0): RGCNConv(50, 50, num_relations=2)
    (1): ELU(alpha=1.0)
    (2): InstanceNorm(50)
    (3): RGCNConv(50, 50, num_relations=2)
    (4): ELU(alpha=1.0)
    (5): InstanceNorm(50)
  )
)
dee_test 2024-03-19 10:27:17,455 [INFO] speos.preprocessing.datasets: HeteroData(
  x=[17024, 93],
  y=[17024],
  train_mask=[17024],
  test_mask=[17024],
  val_mask=[17024],
  gene={ x=[17024, 93] },
  (gene, BioPlex30293T, gene)={ edge_index=[2, 160962] },
  (gene, HuRI, gene)={ edge_index=[2, 79672] }
)
dee_test 2024-03-19 10:27:17,466 [INFO] speos.experiment: Cuda is available: True
dee_test 2024-03-19 10:27:17,475 [INFO] speos.experiment: Created new ResultsHandler pointing to ./results/dee_test.h5
dee_test 2024-03-19 10:27:17,557 [INFO] speos.experiment: Received data with 472 train positives, 14849 train negatives, 27 val positives, 825 val negatives, 26 test positives and 825 test negatives
dee_test 2024-03-19 10:27:17,569 [INFO] speos.experiment: Cuda is available: True
dee_test 2024-03-19 10:27:18,140 [INFO] speos.experiment: Writing TensoBoard data to ./inference/dee_test
dee_test 2024-03-19 10:27:18,164 [INFO] speos.experiment: Writing TensoBoard data to ./runs/dee_test
dee_test 2024-03-19 10:27:18,165 [INFO] speos.experiment: Epoch 0
dee_test 2024-03-19 10:27:19,072 [INFO] speos.experiment: Training Loss: 0.19752761353531006
dee_test 2024-03-19 10:27:19,183 [INFO] speos.experiment: Eval Loss: 0.1955869334767893, Accuracy: 0.9683098591549296, Recall: 0.0, Precision: 0.0, AUROC: 0.5642648709315375, AUPRC: 0.048525054930204266, F1: 0.0, MRR: 0.0006905999482714825, MR: 7382.2962962962965, Target: val
dee_test 2024-03-19 10:27:19,188 [INFO] speos.experiment: Epoch 1
dee_test 2024-03-19 10:27:19,339 [INFO] speos.experiment: Training Loss: 0.19566948456533226
dee_test 2024-03-19 10:27:19,419 [INFO] speos.experiment: Eval Loss: 0.19378082599482915, Accuracy: 0.9683098591549296, Recall: 0.0, Precision: 0.0, AUROC: 0.6541414141414141, AUPRC: 0.06037423079058878, F1: 0.0, MRR: 0.000738733974792639, MR: 5672.62962962963, Target: val
dee_test 2024-03-19 10:27:19,424 [INFO] speos.experiment: Epoch 2
dee_test 2024-03-19 10:27:19,539 [INFO] speos.experiment: Training Loss: 0.19389570524474228
dee_test 2024-03-19 10:27:19,595 [INFO] speos.experiment: Eval Loss: 0.19201297878595033, Accuracy: 0.9683098591549296, Recall: 0.0, Precision: 0.0, AUROC: 0.6540516273849607, AUPRC: 0.07126091545759937, F1: 0.0, MRR: 0.0008800047781917863, MR: 5589.777777777777, Target: val
dee_test 2024-03-19 10:27:19,595 [INFO] speos.experiment: Epoch 3
dee_test 2024-03-19 10:27:19,692 [INFO] speos.experiment: Training Loss: 0.19213943299297576
dee_test 2024-03-19 10:27:19,745 [INFO] speos.experiment: Eval Loss: 0.19008203118331599, Accuracy: 0.9683098591549296, Recall: 0.0, Precision: 0.0, AUROC: 0.6598877665544332, AUPRC: 0.07830256190478563, F1: 0.0, MRR: 0.000981467849303642, MR: 5477.962962962963, Target: val
[...]
``` 

Perhaps there is something wrong with your `tag`? You can try if it runs with the config I just mentioned. You can check the logs if it loads the right labels and/or GWAS and so on.

However, I noticed a mistake in your config, your `mp` keyword has to stand underneath the `model` keyword to work. You can see in my log that it uses RGCNConv instead of FiLMConv layer. Always check the logs to see if the network really looks like you intended. If I change it to the following:

```
name: dee_test

input:
    adjacency: [huri, BioPlex30293T]
model:
  mp:
    type: film
```

I get the correct model in the logs:

```
dee_test 2024-03-19 10:32:21,111 [INFO] speos.experiment: RelationalGeneNetwork(
  (pre_mp): Sequential(
    (0): Linear(93, 50, bias=True)
    (1): ELU(alpha=1.0)
    (2): Linear(50, 50, bias=True)
    (3): ELU(alpha=1.0)
    (4): Linear(50, 50, bias=True)
    (5): ELU(alpha=1.0)
    (6): Linear(50, 50, bias=True)
    (7): ELU(alpha=1.0)
    (8): Linear(50, 50, bias=True)
    (9): ELU(alpha=1.0)
    (10): Linear(50, 50, bias=True)
    (11): ELU(alpha=1.0)
  )
  (post_mp): Sequential(
    (0): Linear(50, 50, bias=True)
    (1): ELU(alpha=1.0)
    (2): Linear(50, 50, bias=True)
    (3): ELU(alpha=1.0)
    (4): Linear(50, 50, bias=True)
    (5): ELU(alpha=1.0)
    (6): Linear(50, 50, bias=True)
    (7): ELU(alpha=1.0)
    (8): Linear(50, 50, bias=True)
    (9): ELU(alpha=1.0)
    (10): Linear(50, 25, bias=True)
    (11): ELU(alpha=1.0)
    (12): Linear(25, 1, bias=True)
  )
  (mp): Sequential(
    (0): FiLMConv(50, 50, num_relations=2)
    (1): ELU(alpha=1.0)
    (2): InstanceNorm(50)
    (3): FiLMConv(50, 50, num_relations=2)
    (4): ELU(alpha=1.0)
    (5): InstanceNorm(50)
  )
)
```

Please let me know if that helped.

Cheers, 
Florin

**Comment by gsh150801** [comment]
I also met this problem. if I use single network, it runs fine. But if I use two or more networks, it print the same error!
This is the error:
```
obesity 2024-03-28 03:00:44,232 [INFO] speos.preprocessing.datasets: Data(x=[17441, 75], edge_index=[2, 169344], y=[17441], train_mask=[17441], test_mask=[17441], val_mask=[17441])
obesity 2024-03-28 03:00:44,245 [INFO] speos.experiment: Cuda is available: True
obesity 2024-03-28 03:00:44,409 [INFO] speos.experiment: Created new ResultsHandler pointing to results/obesity/obesity.h5
obesity 2024-03-28 03:00:44,410 [INFO] speos.experiment: Received data with 76 train positives, 15620 train negatives, 5 val positives, 868 val negatives, 4 test positives and 868 test negatives
obesity 2024-03-28 03:00:44,413 [INFO] speos.experiment: Cuda is available: True
obesity 2024-03-28 03:00:44,992 [INFO] speos.experiment: Writing TensoBoard data to ./inference/obesity
Traceback (most recent call last):
  File "/share1-100G/shguan/projs/dis_gene_pred/speos-master/training.py", line 13, in <module>
    pipeline.run()
  File "/share1-100G/shguan/projs/dis_gene_pred/speos-master/speos/pipeline.py", line 39, in run
    self.experiment.run()
  File "/share1-100G/shguan/projs/dis_gene_pred/speos-master/speos/experiment.py", line 128, in run
    self.train()
  File "/share1-100G/shguan/projs/dis_gene_pred/speos-master/speos/experiment.py", line 163, in train
    self.train_out, loss = self.model.step(self.data, self.data.train_mask)
  File "/share1-100G/shguan/projs/dis_gene_pred/speos-master/speos/models.py", line 213, in step
    out = self(data.x, data.edge_index)
  File "/share1-100G/shguan/projs/dis_gene_pred/speos-master/speos/models.py", line 74, in __call__
    return self.architectures[0](*args, **kwargs)
  File "/share1-100G/shguan/micromamba/envs/speos/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share1-100G/shguan/projs/dis_gene_pred/speos-master/speos/architectures.py", line 408, in forward
    return super().forward(x, edge_index)
  File "/share1-100G/shguan/projs/dis_gene_pred/speos-master/speos/architectures.py", line 325, in forward
    x = self.mp(x_pre, edge_index)
  File "/share1-100G/shguan/micromamba/envs/speos/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/tmp/fanny_pyg/tmpal43f6zc.py", line 18, in forward
    x = self.module_0(x, edge_index)
  File "/share1-100G/shguan/micromamba/envs/speos/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share1-100G/shguan/micromamba/envs/speos/lib/python3.10/site-packages/torch_geometric/nn/conv/rgcn_conv.py", line 204, in forward
    assert edge_type is not None
AssertionError
```

My obesity.yaml:
```
name: obesity

input:
  adjacency: [GRNDB-adipose_tissue,BioPlex30293T]
  tag: obesity
  field: name
  gwas_mappings: ./speos/mapping.json

model:
  mp:
    type: gcn

crossval:
  mode: kfold
  n_folds: 5
  positive_only: True

inference:
  save_dir: results/obesity/
  save_sorted: True
  save_tsv: True

pp:
  save_dir: results/obesity/
```

`./extensions/mapping.json`:
```
[
{  "name": "obesity",
   "ground_truth": "data/mendelian_gene_sets/Body_Mass_Disorder_genes.bed",
   "phenotype": "bodymass_disorder",
   "features_file": "data/gwas/BW.genes.out",
   "function": "test_preprocess_labels",
   "args": ["./extensions/obesity_label_genes.txt"],
   "kwargs": {}
  }
]
```

`./extensions/obesity_label_genes.txt`:
```
MC4R
LEP
POMC
PPARG
LEPR
FTO
PCSK1
UCP3
ENPP1
GHRL
ADRB3
UCP2
INS
CAST
MC3R
BDNF-AS
ADIPOQ
BDNF
SIM1
ADCY3
NR0B2
AGRP
GNAS
AFF4
KIDINS220
NUDC
CARTPT
RETN
H19
PRMT7
NTRK2
ABCC8
FFAR4
SH2B1
IL6
CENPO
GHRLOS
SDC3
PHIP
CDKAL1
AOMS1
CEP19
AQP7
TUB
BBIP1
DYRK1B
INPP5E
CRP
IGF1
AOMS2
PYY
TNF
MEG3
DNMT3A
MT-CYB
SLC6A14
ATP6V0D1-DT
BRCA2
MTTP
SCAPER
OBHP
UCP1
SERPINE1
HSD11B1
POGZ
PDSS1
DNM1L
NRXN1
GLDC
FBXO11
KCNH2
SCN1A
ACSL1
IL17A
GDF15
ACVR2A
ACVR2B
GPR75
TSLP
IL27
HSF1
CD274
SLC29A1
INHBE
EMC10
ADAMTS14
YTHDF1
GPR10
CACNA2D1
GLP1R
DLG4
PICK1
GLCE
IAPP
SOX4
PRDM16
```

[linking of `./data/gwas/BW.genes.out`](https://drive.google.com/file/d/1GrNkNc358GmISmE0_0Rd0LHYNxGoEeOV/view?usp=drive_link)

**Comment by fratajcz** [comment]
Hi guys, sorry for the late reply. I am at a loss here, I made a brand new env and installed the packages that @TamashaM mentioned with python 3.10.14 and the `latest` branch of speos. I tried both your configs and could not reproduce your error. It runs fine for me. 

This is how I installed it:

```
conda create -n speosnew python==3.10.14
conda activate speosnew
conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia
conda install pyg==2.3.1 pytorch-sparse==0.6.17 -c pyg -y

mkdir speos-new
cd speos-new
git clone --recurse-submodules -b latest --single-branch https://github.com/fratajcz/speos.git
cd speos
python3 -m pip install -r requirements.yaml
pip install networkx==2.8.8
pip install .
cp -r ../../speos/data/* data
```
the last step is just copying over the data from the other speos installation so I don't have to download again. You can also just link them here using `ln -s`. I also had to re-install networkx 2.8.8 as the newer version causes trouble. 

Then I had the following environment:

```
$ pip list
Package                 Version
----------------------- -----------
absl-py                 2.1.0
Brotli                  1.0.9
captum                  0.7.0
certifi                 2024.2.2
charset-normalizer      2.0.4
class_resolver          0.4.3
contourpy               1.2.1
cycler                  0.12.1
filelock                3.13.1
fonttools               4.50.0
gmpy2                   2.1.2
grpcio                  1.62.1
h5py                    3.10.0
idna                    3.4
igraph                  0.11.4
Jinja2                  3.1.3
joblib                  1.2.0
kiwisolver              1.4.5
Markdown                3.6
MarkupSafe              2.1.3
matplotlib              3.8.3
mkl-fft                 1.3.8
mkl-random              1.2.4
mkl-service             2.4.0
mpmath                  1.3.0
networkx                2.8.8
numpy                   1.26.4
packaging               24.0
pandas                  2.2.1
patsy                   0.5.6
pillow                  10.2.0
pip                     23.3.1
protobuf                5.26.1
psutil                  5.9.0
pyparsing               3.0.9
PySocks                 1.7.1
python-dateutil         2.9.0.post0
pytz                    2024.1
PyYAML                  6.0.1
requests                2.31.0
scikit-learn            1.3.0
scipy                   1.12.0
seaborn                 0.13.2
setuptools              68.2.2
six                     1.16.0
speos                   0.2.4
statsmodels             0.14.1
sympy                   1.12
tensorboard             2.16.2
tensorboard-data-server 0.7.2
texttable               1.7.0
threadpoolctl           2.2.0
torch                   2.0.1
torch-geometric         2.3.1
torch-scatter           2.1.2
torch-sparse            0.6.17
torchaudio              2.0.2
torchvision             0.15.2
tqdm                    4.65.0
triton                  2.0.0
typing_extensions       4.9.0
tzdata                  2024.1
urllib3                 2.1.0
Werkzeug                3.0.2
wheel                   0.41.2
```

And I could run both your configs, also with the custom nodelist provided by @gsh150801 . I tried it with `training.py -c obesity_config.yaml` and `outer_crossval.py -c obesity_config.yaml`, both worked fine. Did you install it like I did?

However, I noticed some things in your log output, for example this line:

```
obesity 2024-03-28 03:00:44,232 [INFO] speos.preprocessing.datasets: Data(x=[17441, 75], edge_index=[2, 169344], y=[17441], train_mask=[17441], test_mask=[17441], val_mask=[17441])
```

should be the following (from my runs): 
```
obesity 2024-04-03 11:59:41,527 [INFO] speos.preprocessing.datasets: HeteroData(
  x=[17024, 93],
  y=[17024],
  train_mask=[17024],
  test_mask=[17024],
  val_mask=[17024],
  gene={ x=[17024, 93] },
  (gene, BioPlex30293T, gene)={ edge_index=[2, 160962] },
  (gene, GRNDBadiposetissue, gene)={ edge_index=[2, 59329] }
)
```

You number of edges is neither the number of edges in BioPlex nor the sum of both. Did you also get the following line:

```
obesity 2024-04-03 11:59:41,501 [INFO] speos.preprocessing.preprocessor: Using Adjacency matrices: ['BioPlex30293T', 'GRNDBadiposetissue']
```

Or what did it say in the equivalent line? In general I will need more of your log output to help you with your problem. Especially the lines corresponding to input and model configs. And you can also give me your effective config, i.e. the final config that results when your settings are written on top of the default config. It should located in the `model.save_dir` folder and look like this:

```
crossval:
  hold_out_test: true
  key: true
  mode: kfold
  n_folds: 5
  outer_suffix: _outer_{}
  positive_only: true
  seed: 1
  suffix: _fold_{}
cuda: auto
es:
  metric: auroc
  mode: max
  patience: 100
eval:
  cutoff: 0.7
  log_prob_every: 50
  target:
  - train
  - val
inference:
  cutoff_value: 0.7
  gnn_explain: false
  input_explain: false
  key: true
  save: true
  save_dir: results/obesity/
  save_sorted: true
  save_tsv: true
  switch: true
  target: all
input:
  adjacency:
  - GRNDB-adipose_tissue
  - BioPlex30293T
  adjacency_blacklist:
  - recon3d
  - string
  adjacency_field: name
  adjacency_mappings: ./speos/adjacencies.json
  embedding_path: data/misc/walking_all.output
  field: name
  force_multigraph: false
  gene_sets: data/mendelian_gene_sets
  gwas: data/gwas
  gwas_mappings: ./speos/mapping.json
  holdout_positive_only: true
  holdout_size: 0.1
  key: name
  log_expression: false
  main_dir: .
  randomize_adjacency_percent: 0
  save_data: true
  save_dir: ./data/
  tag: obesity
  use_embeddings: false
  use_expression: true
  use_gwas: true
key: obesity
logging:
  dir: ./logs/
  file: auto
  level: 20
model:
  architecture: GeneNetwork
  args: []
  concat_after_mp: false
  kwargs: {}
  loss: bce
  model: SimpleModel
  mp:
    dim: 50
    k: 3
    key: gcn
    kwargs: {}
    n_layers: 2
    nheads: null
    normalize: instance
    type: rgcn
  plot: true
  plot_dir: ./plots/
  post_mp:
    act: elu
    dim: 50
    dropout: null
    n_layers: 5
    normalize: null
    type: fc
  pre_mp:
    act: elu
    dim: 50
    dropout: null
    n_layers: 5
    normalize: null
    type: fc
  regularization_lambda: 0.01
  save: true
  save_dir: ./models/
  skip: false
  skip_mp: false
name: obesity
optim:
  lr: 0.001
  measure: loss
  target: val
pp:
  consensus: top_down
  cutoff_type: split
  cutoff_value: 0.7
  key: results/obesity/
  plot: true
  plot_dir: ./plots/
  save: true
  save_dir: results/obesity/
  switch: true
  tasks:
  - overlap_analysis
  - dge
  - pathway
  - hpo_enrichment
  - go_enrichment
  - drugtarget
  - druggable
  - mouseKO
  - lof_intolerance
scheduler:
  factor: 0.33
  limit: 0.0001
  mode: max
  patience: 25
timestamp: 1712146745.2882788
training:
  dilution: 10
  max_epochs: 1000
  pos_weight: 2
  switch: true

```
